name: validation
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install esphome==2026.7.1
      - run: ./scripts_validate.sh
      - run: esphome compile examples/gree-livo-gen3-receive-only.yaml
      - run: esphome compile examples/gree-livo-gen3-poll-only.yaml
      - run: esphome compile examples/gree-livo-gen3-control.yaml
